package com.sentinel.rules.model

enum class EventKind { SPLASH_SKIPPED, POPUP_CLOSED, REWARDED_SILENCED, JUMP_REVERTED,
    DNS_BLOCKED, HTTPDNS_REJECTED, NOTIFICATION_CANCELLED, SYSTEM_OP, AUTO_RENEW_WARNED, WOULD_BLOCK }
